name : 05 - 2 - Event Filters and Activity Types
on: 
  pull_request:
    types: closed
    branches:
        master

jobs:
  Echodisplay:
         runs-on: ubuntu-latest
         steps:
            - name: Echodisplay
              run:
                echo "Running whenever a PR is closed"
 