name: 07 - Using Expressions
run-name: 07 - using Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF' }}
env: 
    MY_VAR_WITH_DEFAULT: ${{vars.MY_VAR || 'default_values' }}
on: 
   #push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{inputs.debug}}
              run: |
               echo "Triggered by: ${{github.event_name}}""
               echo "Branch: ${{github.ref}}""
               echo "Commit SHA: ${{github.sha}}""
               echo "Runner OS: ${{runner.os}}


            - name: Print when triggered from master
              if: ${{inputs.debug && github.ref == 'refs/heads/master' }}
              run: echo "I was triggered from master"

            - name: Greeting
              run: echo "Hello World"

