name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step

            node-version:
                type: choice
                options:
                    - '18.x'
                    - '20.x'
                    - '21.x'
                default: '20.x'
                
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory : 13-Caching/react-app
        steps:
            - name: Checkout code
              uses: Actions/Checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}

            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache            
              with:
                path: 13-Caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('13-Caching/react-app/package-lock.json') }}
         
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install

            - name: Testing
              run: npm run test

            - name: Building
              run: npm run build

            - name: DEploying to non-prod
              run: echo "Deploying to nonprod"


              
    

